# See https://containers.dev/guide/dockerfile
ARG VARIANT=20
FROM mcr.microsoft.com/devcontainers/javascript-node:0-${VARIANT}

# Install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends 1password-cli

# Install additional global node packages
# RUN su node -c "npm install -g wrangler"